# Generated by Django 3.0 on 2019-12-13 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=32, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=255)),
                ('filesize', models.IntegerField()),
                ('graph_file', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('imports', models.TextField()),
                ('informations', models.TextField()),
                ('file_type', models.TextField()),
                ('nb_loots', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LootTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LootModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loots', to='api.FileModel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loots', to='api.LootTypeModel')),
            ],
        ),
        migrations.CreateModel(
            name='FirmwareModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('model', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('filesize', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmwares', to='api.BrandModel')),
            ],
        ),
        migrations.AddField(
            model_name='filemodel',
            name='firmware',
            field=models.ManyToManyField(related_name='files', to='api.FirmwareModel'),
        ),
    ]
